name: 'Check review status'

on:
  pull_request_review:
    types: [submitted, edited, dismissed]
  pull_request: {}

jobs:
  # This job sets that the PR satisfies review condition as an output.
  # This job always finishes successfully.
  check_review_status:
    runs-on: 'ubuntu-latest'
    outputs:
      can_merge: ${{ steps.check_review_status.outputs.can_merge }}
    permissions:
      pull-requests: read
      contents: read
    env:
      BASE_SHA: ${{ github.event.pull_request.base.sha }}
      HEAD_SHA: ${{ github.event.pull_request.head.sha }}
      PR_AUTHOR: ${{ github.event.pull_request.user.login }}
      GH_REPO: ${{ github.repository }}
    steps:
      - uses: actions/checkout@v4
        with:
          filter: 'blob:none'
          fetch-depth: 0
          ref: main
      - name: Changed gems and non gem files
        id: changes
        run: |
          ruby .github/workflows/pr_bot/changed_files.rb
      - name: Check and set review status
        id: check_review_status
        env:
          CHANGED_GEMS: ${{ steps.changes.outputs.gems }}
          CHANGED_NON_GEMS: ${{ steps.changes.outputs.non_gems }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ruby .github/workflows/pr_bot/check_review_status.rb "$CHANGED_GEMS" "$CHANGED_NON_GEMS" "$PR_NUMBER"

  # This job finishes successfully if the PR satisfies reviewing condition.
  # Otherwise, this job is skipped.
  review_status:
    runs-on: 'ubuntu-latest'
    needs: check_review_status
    if: ${{ !needs.check_review_status.outputs.can_merge }}
    steps:
      - name: Finish successfully
        run: 'true'
