name: Comment on review

on:
  workflow_run:
    workflows: [Generate comment body on review]
    types: [completed]


jobs:
  comment:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      pull-requests: write
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: comment_body_on_review
          run-id: ${{ github.event.workflow_run.id}}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Send a comment
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run:
          gh pr comment "$PR_NUMBER" --body "$(cat COMMENT_BODY.txt)" --repo "$GH_REPO"

