name: 'Comment on new review'

on:
  pull_request_review:
    types: [submitted]

jobs:
  create_comment:
    if: github.event.review.state == 'APPROVED'
    runs-on: 'ubuntu-latest'
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Send a comment
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run:
          gh pr comment "$PR_NUMBER" --body "test" --repo "$GH_REPO"
