name: 'Comment on new review'

on:
  pull_request_review:
    types: [submitted]

jobs:
  create_comment:
    if: github.event.review.state == 'APPROVED'
    runs-on: 'ubuntu-latest'
    permissions:
      pull-requests: write
      contents: read
    env:
      BASE_SHA: ${{ github.event.pull_request.base.sha }}
      HEAD_SHA: ${{ github.event.pull_request.head.sha }}
      PR_AUTHOR: ${{ github.event.pull_request.user.login }}
      GH_REPO: ${{ github.repository }}
    steps:
      - uses: actions/checkout@v4
        with:
          filter: 'blob:none'
          fetch-depth: 0
          ref: main
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
      - name: Changed gems and non gem files
        id: changes
        run: |
          ruby .github/workflows/pr_bot/changed_files.rb
      - name: Prepare comment body
        id: comment-body
        env:
          CHANGED_GEMS: ${{ steps.changes.outputs.gems }}
          CHANGED_NON_GEMS: ${{ steps.changes.outputs.non_gems }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REVIEWED_BY: ${{ github.event.review.user.login }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ruby .github/workflows/pr_bot/review_result_comment_body.rb "$CHANGED_GEMS" "$CHANGED_NON_GEMS" "$PR_NUMBER"
      - name: Send a comment
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          COMMENT_BODY: ${{ steps.comment-body.outputs.comment_body }}
        run:
          gh pr comment "$PR_NUMBER" --body "$COMMENT_BODY" --repo "$GH_REPO"
