name: Comment on review

on:
  workflow_run:
    workflows: [Generate comment body on review]
    types: [completed]


jobs:
  comment:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      pull-requests: write
    steps:
      - name: Download artifact
        with:
          name: comment_body_on_review
          run-id: ${{ github.event.workflow_run.id}}
      - name: Send a comment
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          COMMENT_BODY: ${{ steps.comment-body.outputs.comment_body }}
        run:
          gh pr comment "$PR_NUMBER" --body "$(cat COMMENT_BODY.txt)" --repo "$GH_REPO"

